#!/bin/bash

export LOGFILE="/root/download_packages.log"

download_package() {
	export DEBIAN_FRONTEND=noninteractive 
	 apt-get install --reinstall --download-only -y $1

	if [ $? -ne 0 ]; then
		echo -e "${1} - fail" >> $LOGFILE
	else
		echo -e "${1} - success" >> $LOGFILE
	fi
}

if [ ! -f $LOGFILE ]; then
	echo -n "" > $LOGFILE
fi

declare -a List=(
		"alsa-utils"
		"apt-transport-https"
		"arping"
		"arptables"
		"attr"
		"autoconf"
		"automake"
		"autotools-dev"
		"bc"
		"bind9"
		"bind9utils"
		"bluetooth"
		"bluez"
		"bluez-tools"
		"bridge-utils"
		"build-essential"
		"bzip2"
		"ca-certificates"
		"cifs-utils"
		"cpufrequtils"
		"curl"
		"debhelper"
		"dialog"
		"dirmngr"
		"dnsutils"
		"docbook-xsl"
		"dos2unix"
		"dosfstools"
		"e2fsprogs"
		"ethtool"
		"expect"
		"figlet"
		"genisoimage"
		"geoip-database"
		"gettext"
		"git"
		"gnupg"
		"gzip"
		"hostapd"
		"ifenslave"
		"ifmetric"
		"ifupdown"
		"iptables"
		"iptables-dev"
		"iptraf"
		"iptraf-ng"
		"iputils-arping"
		"isatapd"
		"isc-dhcp-client"
		"isc-dhcp-server"
		"iw"
		"libdrm2"
		"libdrm-common"
		"libdrm-dev"
		"libfsntfs-utils"
		"libnss-winbind"
		"libpam0g"
		"libpam-winbind"
		"libsysfs-dev"
		"libtool"
		"libunwind8"
		"lprng"
		"lsb-base"
		"lsb-core"
		"lsb-release"
		"lshw"
		"macchanger"
		"man"
		"mc"
		"net-tools"
		"ntfs-3g"
		"ntp"
		"ntpdate"
		"parted"
		"pkg-config"
		"python"
		"python3"
		"resolvconf"
		"rfkill"
		"rsync"
		"samba"
		"samba-common"
		"scrounge-ntfs"
		"sendmail-base"
		"smbclient"
		"software-properties-common"
		"subversion"
		"systemd"
		"tasksel"
		"toilet"
		"u-boot-tools"
		"ucarp"
		"util-linux"
		"vim"
		"vim"
		"vlan"
		"wakeonlan"
		"wide-dhcpv6-client"
		"wide-dhcpv6-server"
		"winbind"
		"wireless-tools"
		"wpasupplicant"
		"xutils-dev"
		"xzip"
		"xz-utils"
		"nfs-kernel-server"
		"llvm"
		"clang"
		"mysql"
		"postgresql"
		"nginx"
		"apt-offline"
		"ntfs-config"
		"hostap-utils" 
		"sudo"
		"libjpeg-dev"
		"iperf"
		"iperf3"
		"locales"
		"netbase"
		"ssh"
		"less"
		"fbset"
		"psmisc"
		"strace"
		"ed"
		"ncdu"
		"crda"
		"console-setup"
		"keyboard-configuration"
		"debconf-utils"
		"unzip"
		"manpages-dev"
		"bash-completion"
		"gdb"
		"v4l-utils"
		"avahi-daemon"
		"lua5.1"
		"luajit"
		"hardlink"
		"fake-hwclock"
		"nfs-common"
		"usbutils"
		"dphys-swapfile"
		"apt-listchanges"
		"usb-modeswitch"
		"libpam-chksshpwd"
		"libmtp-runtime"
		"htop"
		"man-db"
		"policykit-1"
		"ssh-import-id"
		"rng-tools"
		)

apt-get -y autoremove
apt-get -y update

for package in "${List[@]}";
   do
	 echo "downloading ${package}"
	 download_package $package
   done
